### ISSUE TITLE
Use Case: Alternative interfaces

### ISSUE THREAD

**Issue by jtc42** [w3c/web-thing-protocol#13]
As a WoT client developer I want to know which top level links correspond to alternative (e.g. graphical HTML) interfaces so that I can integrate a Things built in graphical interfaces into my client.

This may be out of spec for this charter? Would be useful to have a SHOULD on this so we know what links clients should be looking for to get specific interfaces.

**Comment by benfrancis** [comment]
I think you might be right that this may be out of scope for the Web Thing Protocol charter. Note that this is already possible using a Thing Description. Mozilla does it with a link relation like this:

```
"links": [
  {
    "rel": "alternate",
    "mediaType": "text/html",
    "href": "/things/lamp"
  }
]
```

This is given as an [example](https://iot.mozilla.org/wot/#example-6-example-links-member) in Mozilla's Web Thing API specification, but it's not a W3C recommendation as such. I'm not sure what the right home for this is, but my first thought would be to suggest this for the [W3C Thing Description specification](https://github.com/w3c/wot-thing-description), perhaps as a non-normative note.

**Comment by jtc42** [comment]
Okay yeah that makes sense. I did think it was on the edge of being irrelevant here. I noticed the Mozilla example which is what made me think it's worth checking.

Thanks! Happy to close this now given the scope.
