### ISSUE TITLE
Multiple affordances of a web thing over a single WebSocket connection

### ISSUE THREAD

**Issue by jtc42** [w3c/web-thing-protocol#6]
Hi all,

In the existing use-case document, section 3.2.1.2 specifies that Things "SHOULD define a way for a WoT client to carry out operations on multiple affordances of a web thing over a single WebSocket connection"

I'm unsure how concrete the "SHOULD" is here, but I wonder if this might be changed to MUST. My concern is that failing to implement this might lead to multiple WS routes, with one route per affordance. 

Our current applications will require some method of communication without the overhead of HTTP headers on every request, which would necessitate a single WS route that can be held open and used to an arbitrary series of interactions.

This seems to be how the Mozilla implementation currently operates, but there's pecious little information on how this should be implemented in the W3C spec. 

For us, it will be really critical going forward. It would be great to get some thoughts or clarification on this point.

**Comment by benfrancis** [comment]
Thanks very much for the feedback.

I agree from experience this is a MUST, fixed in https://github.com/w3c/web-thing-protocol/pull/8

**Comment by jtc42** [comment]
Brilliant, thank you!
